// <auto-generated />
using System;
using BooksApi.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BooksApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BooksApi.Models.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            AuthorName = "J. R. R. Tolkien",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1892, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathDate = new DateTime(1973, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            AuthorName = "George R.R. Martin",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1948, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            AuthorName = "Stephanie Meyer",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1973, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6L,
                            AuthorName = "J.K. Rowling",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7L,
                            AuthorName = "Remigiusz Mróz",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1987, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8L,
                            AuthorName = "Henryk Sienkiewicz",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1846, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathDate = new DateTime(1916, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9L,
                            AuthorName = "Bolesław Prus",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1847, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathDate = new DateTime(1912, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10L,
                            AuthorName = "Władysław Reymont",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1867, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathDate = new DateTime(1925, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11L,
                            AuthorName = "Andrzej Sapkowski",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1948, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12L,
                            AuthorName = "Stephan King",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1947, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13L,
                            AuthorName = "E.L. James",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1963, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14L,
                            AuthorName = "Alicja Sinicka",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1987, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15L,
                            AuthorName = "William Shakespeare",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1564, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathDate = new DateTime(1616, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16L,
                            AuthorName = "Juliusz Słowacki",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1809, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeathDate = new DateTime(1949, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17L,
                            AuthorName = "Olga Tokarczuk",
                            Biography = "Lorem Ipsum Dolor Sit Amet",
                            BirthDate = new DateTime(1962, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BooksApi.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 3L,
                            Description = "Best book that was ever written.",
                            GenreId = 1L,
                            Title = "Lord of the rings"
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 4L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 1L,
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 3L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 1L,
                            Title = "Hobbit"
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = 5L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 1L,
                            Title = "Twilight"
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = 6L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 1L,
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = 16L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 5L,
                            Title = "Balladyna"
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = 15L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 5L,
                            Title = "Król Lear"
                        },
                        new
                        {
                            Id = 10L,
                            AuthorId = 14L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 4L,
                            Title = "Oczy wilka"
                        },
                        new
                        {
                            Id = 11L,
                            AuthorId = 13L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 4L,
                            Title = "Fifty Shades of Grey"
                        },
                        new
                        {
                            Id = 12L,
                            AuthorId = 12L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 2L,
                            Title = "Smętarz dla zwierzaków"
                        },
                        new
                        {
                            Id = 13L,
                            AuthorId = 12L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 2L,
                            Title = "It"
                        },
                        new
                        {
                            Id = 14L,
                            AuthorId = 7L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 3L,
                            Title = "Halny"
                        },
                        new
                        {
                            Id = 15L,
                            AuthorId = 10L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 6L,
                            Title = "Chłopi"
                        },
                        new
                        {
                            Id = 16L,
                            AuthorId = 9L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 5L,
                            Title = "Lalka"
                        },
                        new
                        {
                            Id = 17L,
                            AuthorId = 8L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 6L,
                            Title = "Potop"
                        },
                        new
                        {
                            Id = 19L,
                            AuthorId = 17L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 7L,
                            Title = "Bieguni"
                        },
                        new
                        {
                            Id = 24L,
                            AuthorId = 11L,
                            Description = "Lorem Ipsum Dolor Sit Amet",
                            GenreId = 1L,
                            Title = "Wiedźmin"
                        });
                });

            modelBuilder.Entity("BooksApi.Models.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("GenreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            Id = 2L,
                            GenreName = "Horror"
                        },
                        new
                        {
                            Id = 3L,
                            GenreName = "Criminal"
                        },
                        new
                        {
                            Id = 4L,
                            GenreName = "Romance"
                        },
                        new
                        {
                            Id = 5L,
                            GenreName = "Drama"
                        },
                        new
                        {
                            Id = 6L,
                            GenreName = "Historic"
                        },
                        new
                        {
                            Id = 7L,
                            GenreName = "Slice of life"
                        });
                });

            modelBuilder.Entity("BooksApi.Models.Opinion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Rate")
                        .HasColumnType("boolean");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Opinions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Rate = false,
                            ReviewId = 1L,
                            UserId = "23e1a0ef-4a8a-462a-8219-1d3a1169f417"
                        },
                        new
                        {
                            Id = 2L,
                            Rate = false,
                            ReviewId = 2L,
                            UserId = "593a9e65-5f4d-40b8-91f5-1813f577ce70"
                        },
                        new
                        {
                            Id = 3L,
                            Rate = false,
                            ReviewId = 5L,
                            UserId = "509de9d8-a3d5-47d9-a6b2-82c13c5dd216"
                        },
                        new
                        {
                            Id = 4L,
                            Rate = true,
                            ReviewId = 8L,
                            UserId = "e6f1d790-fa08-4db8-8958-4d8d171193d2"
                        },
                        new
                        {
                            Id = 5L,
                            Rate = true,
                            ReviewId = 4L,
                            UserId = "7b2e5361-9196-49f7-aa93-9c752fd63f19"
                        },
                        new
                        {
                            Id = 6L,
                            Rate = false,
                            ReviewId = 10L,
                            UserId = "1e6751b3-ecd8-4835-aee7-29274771601d"
                        },
                        new
                        {
                            Id = 7L,
                            Rate = false,
                            ReviewId = 5L,
                            UserId = "e32bdbc1-1892-4e41-9c69-6fcf8e40635c"
                        },
                        new
                        {
                            Id = 8L,
                            Rate = true,
                            ReviewId = 4L,
                            UserId = "bdf0715a-053f-4d3a-85e5-8013f853107e"
                        },
                        new
                        {
                            Id = 9L,
                            Rate = false,
                            ReviewId = 9L,
                            UserId = "fb5fad4f-130e-439a-a74d-e75432c8a5d7"
                        },
                        new
                        {
                            Id = 10L,
                            Rate = false,
                            ReviewId = 3L,
                            UserId = "1e1a1a16-3c37-467f-ac77-e83f3061edd3"
                        },
                        new
                        {
                            Id = 11L,
                            Rate = false,
                            ReviewId = 11L,
                            UserId = "1fe1d8b9-40b4-4d21-9ec3-747b25fe0316"
                        },
                        new
                        {
                            Id = 12L,
                            Rate = true,
                            ReviewId = 7L,
                            UserId = "0cf44c1c-6a00-4738-b33f-b662cf98cd7e"
                        },
                        new
                        {
                            Id = 13L,
                            Rate = false,
                            ReviewId = 12L,
                            UserId = "a6592ad5-0033-4d24-b5c7-b5ab43d81836"
                        },
                        new
                        {
                            Id = 14L,
                            Rate = false,
                            ReviewId = 13L,
                            UserId = "36e158e5-3731-4976-a13f-445fe61fdddd"
                        },
                        new
                        {
                            Id = 15L,
                            Rate = true,
                            ReviewId = 3L,
                            UserId = "4be99f35-6aa1-46b4-b0d0-2c0a6545a9e2"
                        },
                        new
                        {
                            Id = 16L,
                            Rate = true,
                            ReviewId = 7L,
                            UserId = "c907b3e5-3ebc-4bf0-a733-b01c75ba8d77"
                        },
                        new
                        {
                            Id = 17L,
                            Rate = false,
                            ReviewId = 3L,
                            UserId = "9c3d4bdf-a2eb-42f5-9b67-07facff0653d"
                        });
                });

            modelBuilder.Entity("BooksApi.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiryOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("RevokedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BooksApi.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BookId = 1L,
                            Content = "I think that is the best book ever written",
                            Rate = 10,
                            Title = "My favourite book",
                            UserId = "23e1a0ef-4a8a-462a-8219-1d3a1169f417"
                        },
                        new
                        {
                            Id = 2L,
                            BookId = 7L,
                            Content = "Gra oparta na tej książce, wygląda jakby w ogóle nie była przemyślana.",
                            Rate = 3,
                            Title = "Beznadziejna gra",
                            UserId = "593a9e65-5f4d-40b8-91f5-1813f577ce70"
                        },
                        new
                        {
                            Id = 3L,
                            BookId = 4L,
                            Content = "Bohaterowie tej książki są napisani w perfekcyjny sposób.",
                            Rate = 10,
                            Title = "Najlepsi bohaterowie",
                            UserId = "7b2e5361-9196-49f7-aa93-9c752fd63f19"
                        },
                        new
                        {
                            Id = 4L,
                            BookId = 13L,
                            Content = "Ulubiony bohater.",
                            Rate = 10,
                            Title = "Ulubiony bohater.",
                            UserId = "7493442e-646b-41d4-8aa8-8b764c12eb2c"
                        },
                        new
                        {
                            Id = 5L,
                            BookId = 11L,
                            Content = "Książka jest nudna i nieciekawa dla czytelnika",
                            Rate = 1,
                            Title = "Niezbyt dobra opinia",
                            UserId = "e6f1d790-fa08-4db8-8958-4d8d171193d2"
                        },
                        new
                        {
                            Id = 6L,
                            BookId = 8L,
                            Content = "W tej książce można rzenieść się w naprawdę magiczne miejsca i poznać prawdziwych bohaterów.",
                            Rate = 9,
                            Title = "Magiczne miejsce.",
                            UserId = "a6592ad5-0033-4d24-b5c7-b5ab43d81836"
                        },
                        new
                        {
                            Id = 7L,
                            BookId = 6L,
                            Content = "Z tej książki można naprawdę wiele się nauczyć.",
                            Rate = 8,
                            Title = "Cięte riosty.",
                            UserId = "c907b3e5-3ebc-4bf0-a733-b01c75ba8d77"
                        },
                        new
                        {
                            Id = 8L,
                            BookId = 9L,
                            Content = "Nie spodziewałam się, ze książka tej autorki może być tak dobra.",
                            Rate = 8,
                            Title = "Miła niespodzianka",
                            UserId = "1e1a1a16-3c37-467f-ac77-e83f3061edd3"
                        },
                        new
                        {
                            Id = 9L,
                            BookId = 16L,
                            Content = "Brakuje mi w tej książce prawdziwych zwrotów akcji.",
                            Rate = 5,
                            Title = "Zwroty akcji",
                            UserId = "509de9d8-a3d5-47d9-a6b2-82c13c5dd216"
                        },
                        new
                        {
                            Id = 10L,
                            BookId = 15L,
                            Content = "W tej książce mogą naprawdę odnaleźć się prawdziwi miłośnicy historii.",
                            Rate = 9,
                            Title = "Miłośnicy historii.",
                            UserId = "0cf44c1c-6a00-4738-b33f-b662cf98cd7e"
                        },
                        new
                        {
                            Id = 11L,
                            BookId = 10L,
                            Content = "Autor miał chyba ograniczoną wyobraźnię pisząć tę książkę.",
                            Rate = 2,
                            Title = "Możliwości wyobraźni",
                            UserId = "e32bdbc1-1892-4e41-9c69-6fcf8e40635c"
                        },
                        new
                        {
                            Id = 12L,
                            BookId = 12L,
                            Content = "Dzięki dokładnym opisą przyrody i otoczenia czytelnik może przenieść do świata powieśći.",
                            Rate = 8,
                            Title = "Moc słów.",
                            UserId = "e32bdbc1-1892-4e41-9c69-6fcf8e40635c"
                        },
                        new
                        {
                            Id = 13L,
                            BookId = 17L,
                            Content = "Żałuję, że ta książka się już skończyła,bo bardzo się w nią wciągnęłam.",
                            Rate = 9,
                            Title = "Tylko tyle?",
                            UserId = "509de9d8-a3d5-47d9-a6b2-82c13c5dd216"
                        },
                        new
                        {
                            Id = 14L,
                            BookId = 5L,
                            Content = "Ta seria książek trwa już za długo,mam nadzieję,że to ostatnia.",
                            Rate = 3,
                            Title = "Oby to już koniec.",
                            UserId = "c907b3e5-3ebc-4bf0-a733-b01c75ba8d77"
                        },
                        new
                        {
                            Id = 15L,
                            BookId = 5L,
                            Content = "Ta książka potrafi narawdę dobrze przestraszyć.",
                            Rate = 1,
                            Title = "Prawdziwy horror.",
                            UserId = "c907b3e5-3ebc-4bf0-a733-b01c75ba8d77"
                        },
                        new
                        {
                            Id = 16L,
                            BookId = 11L,
                            Content = "Książka, która trzyma tajemnice do samego końca i daje nieoczekiwane zwroty akcji to dobra książka.",
                            Rate = 10,
                            Title = "To niemożliwe.",
                            UserId = "e6f1d790-fa08-4db8-8958-4d8d171193d2"
                        },
                        new
                        {
                            Id = 17L,
                            BookId = 15L,
                            Content = "Myślałem, że przyadnie mita ksiązka do gustu, ale jednak się pomyliłem.",
                            Rate = 3,
                            Title = "To nie to.",
                            UserId = "7493442e-646b-41d4-8aa8-8b764c12eb2c"
                        });
                });

            modelBuilder.Entity("BooksApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "23e1a0ef-4a8a-462a-8219-1d3a1169f417",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f8c1f8d-ea3c-455c-8865-9a19cd32569a",
                            Email = "stafano@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFANO@GMAIL.COM",
                            NormalizedUserName = "STEFFFANO1",
                            PasswordHash = "AQAAAAEAACcQAAAAEAHFYHGeTTlZ4xTbt8KltK1pAvIWf+CmJ2jA1BucMApcnwKbC7kiJJZM+MNhYx9Log==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f9f964a-88e8-45db-800a-57642d900501",
                            TwoFactorEnabled = false,
                            UserName = "Stefffano1"
                        },
                        new
                        {
                            Id = "593a9e65-5f4d-40b8-91f5-1813f577ce70",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b538d2a5-7e17-41d6-bdda-6794a6456698",
                            Email = "martink@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARTINK@GMAIL.COM",
                            NormalizedUserName = "MARTINX",
                            PasswordHash = "AQAAAAEAACcQAAAAEIbHNTScInLCzoPo/sIPgeSvPFNTk/N3g6lWMytqWezvjX08rHU8uIc1+wzgisQNYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43c5c256-d308-4bd9-b586-834397eacd16",
                            TwoFactorEnabled = false,
                            UserName = "Martinx"
                        },
                        new
                        {
                            Id = "509de9d8-a3d5-47d9-a6b2-82c13c5dd216",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02719bdd-70e8-4888-9885-4eea21513f20",
                            Email = "mich@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MICH@GMAIL.COM",
                            NormalizedUserName = "MICHAELLLO",
                            PasswordHash = "AQAAAAEAACcQAAAAENsOwHoexrbamG2Eg+jm9vrowRjcb/Hs9N4TSAP3Jgrt2GJ1BH3pBlk8xtZDewUKhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77462246-3813-45e9-a9cf-71351303dec4",
                            TwoFactorEnabled = false,
                            UserName = "Michaelllo"
                        },
                        new
                        {
                            Id = "e6f1d790-fa08-4db8-8958-4d8d171193d2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7e74cf8-5ae9-4176-ab9f-7959f939b819",
                            Email = "a.one@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "A.ONE@GMAIL.COM",
                            NormalizedUserName = "ANNA",
                            PasswordHash = "AQAAAAEAACcQAAAAEAnjlD3KIOY2Xgpq3zKmV6HmKNzBk+f4Cg0SBUqg1jZmH4fcQwOq0QBU1/AqZiLPlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b347cdea-f8eb-4f43-96ae-69cc410184d2",
                            TwoFactorEnabled = false,
                            UserName = "Anna"
                        },
                        new
                        {
                            Id = "7b2e5361-9196-49f7-aa93-9c752fd63f19",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f7ca58e-615a-4721-b79c-1fb954cd20ee",
                            Email = "sara12@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA12@GMAIL.COM",
                            NormalizedUserName = "SARA12",
                            PasswordHash = "AQAAAAEAACcQAAAAEB1oCK8TJdhRtUF1/zrUmi0/fyW8JtqbvGKKLyJK10GMPFAJXyQQqkhy+Dn8iLlzng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d659a3b-a923-4f27-8b57-1faa975dfaf9",
                            TwoFactorEnabled = false,
                            UserName = "Sara12"
                        },
                        new
                        {
                            Id = "1e6751b3-ecd8-4835-aee7-29274771601d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0dc2f08-9294-44d5-8c68-254e7de85c3c",
                            Email = "t.smith@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "T.SMITH@GMAIL.COM",
                            NormalizedUserName = "TIMIX",
                            PasswordHash = "AQAAAAEAACcQAAAAENUx8dIbE2A7Fl6aGLhBPyDh5I8Awj3IhOeLrjG4io1vluRKvQKlLS6Tz7mhwV7zOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fefd15f8-0277-4120-8b96-a4d36d7a2b91",
                            TwoFactorEnabled = false,
                            UserName = "Timix"
                        },
                        new
                        {
                            Id = "e32bdbc1-1892-4e41-9c69-6fcf8e40635c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd97284c-7e58-4f3f-860b-68c6d53febef",
                            Email = "norbi.m@gamil.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NORBI.M@GAMIL.COM",
                            NormalizedUserName = "NORBI",
                            PasswordHash = "AQAAAAEAACcQAAAAEDRFrzfIG143H3HVHxguEs9I5l0GaKb+hwfX3/VDIozpfWV7WV3bCEHYsYrWdyd0rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb0ee692-d74c-4a47-818a-4ad0fa6f9097",
                            TwoFactorEnabled = false,
                            UserName = "Norbi"
                        },
                        new
                        {
                            Id = "7493442e-646b-41d4-8aa8-8b764c12eb2c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ebac61b2-4fd1-4ecc-ad65-af85aebfdfd1",
                            Email = "ewarak@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EWARAK@GMAIL.COM",
                            NormalizedUserName = "EWAAAA",
                            PasswordHash = "AQAAAAEAACcQAAAAEH2P3mYJmZan0OlKW8gxz3YMdhkox2bWHAwQyeskF1ok1k8uOgmB3fiFzZrAo7vMIg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68e1231c-25b7-486d-b101-a203a3503ce4",
                            TwoFactorEnabled = false,
                            UserName = "Ewaaaa"
                        },
                        new
                        {
                            Id = "4be99f35-6aa1-46b4-b0d0-2c0a6545a9e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d160a1a-685d-4b99-8cef-ce19cfd8cba1",
                            Email = "j.fik@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "J.FIK@GMAIL.COM",
                            NormalizedUserName = "JANEK99",
                            PasswordHash = "AQAAAAEAACcQAAAAEFgywC9rr5W8PnmrybBItP4z6lZgoRyNFsowX2QihVgKVcF6AOt4pDfoOqu423dBaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7d0dd088-da81-498d-8523-970bfef49ddf",
                            TwoFactorEnabled = false,
                            UserName = "Janek99"
                        },
                        new
                        {
                            Id = "a6592ad5-0033-4d24-b5c7-b5ab43d81836",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7fd178d-735d-4c0d-932d-e2cef56c6e89",
                            Email = "ewelina99@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EWELINA99@GMAIL.COM",
                            NormalizedUserName = "EWELCIA",
                            PasswordHash = "AQAAAAEAACcQAAAAEAORKT4C8Oap19PpHE+Zzsz3wCo6ZsDnALUdTCMBMLMfCbNS8dr2+NF7r71DSdvcQA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e77824b-3d15-4cf3-af36-f6420a0667cf",
                            TwoFactorEnabled = false,
                            UserName = "Ewelcia"
                        },
                        new
                        {
                            Id = "c907b3e5-3ebc-4bf0-a733-b01c75ba8d77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58fc7909-e412-4805-9d68-a2d3746fc110",
                            Email = "wiktoria@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "WIKTORIA@GMAIL.COM",
                            NormalizedUserName = "WIKA",
                            PasswordHash = "AQAAAAEAACcQAAAAECSWiSOxnH69A+p4SW7FhKR/Hn35IxmgaXULJ3X403Djjfy+8ZAhX90Fu8F3ZEFm5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5892ec31-6b2b-4e9d-bb14-922b26e57456",
                            TwoFactorEnabled = false,
                            UserName = "Wika"
                        },
                        new
                        {
                            Id = "0cf44c1c-6a00-4738-b33f-b662cf98cd7e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8c3b1fb3-0c9d-4c0a-a70b-ca61768848ae",
                            Email = "rzeka.magda@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RZEKA.MAGDA@GMAIL.COM",
                            NormalizedUserName = "MADZIX",
                            PasswordHash = "AQAAAAEAACcQAAAAEGbFlqlPkedpfCjKtg+uB75EhcGtws5iCALJN9EeNHWPetdoPGVsQr22j0gR1HXaaA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ae0ce89-2f0e-4c57-883f-f2bb661ec749",
                            TwoFactorEnabled = false,
                            UserName = "Madzix"
                        },
                        new
                        {
                            Id = "1e1a1a16-3c37-467f-ac77-e83f3061edd3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed42356a-eaf0-486a-adf5-51b4f193b5e0",
                            Email = "w.wrak@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "W.WRAK@GMAIL.COM",
                            NormalizedUserName = "WERCIA",
                            PasswordHash = "AQAAAAEAACcQAAAAEJjdAD6xl+Sjymg3yzA4t6QFbdYVKqWPJlvIpxCCpeR/SXJUznPsQGFMmJv69K+IEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6eb5631-e0ef-4d5e-82c6-17a2d336b958",
                            TwoFactorEnabled = false,
                            UserName = "Wercia"
                        },
                        new
                        {
                            Id = "1fe1d8b9-40b4-4d21-9ec3-747b25fe0316",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2d8ca985-dd0a-4752-84fc-5c64629523e1",
                            Email = "marcinp@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MARCINP@GMAIL.COM",
                            NormalizedUserName = "PANMARCIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJzclUnYri1R0JvSw9UjzzzycRKvGfDQnGOz8vxzNseogTUFcqUOSDkj1t+aU3Ug9A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7d17961b-d9a1-45fa-a533-b9ccab3d0e82",
                            TwoFactorEnabled = false,
                            UserName = "PanMarcin"
                        },
                        new
                        {
                            Id = "fb5fad4f-130e-439a-a74d-e75432c8a5d7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ccd4b8de-2ff8-4035-b9eb-03b8c633e7a5",
                            Email = "znawca@gamil.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZNAWCA@GAMIL.COM",
                            NormalizedUserName = "ZNAWCA",
                            PasswordHash = "AQAAAAEAACcQAAAAEDjGY5fnWiv1HkUxQOATx7rjSBbKk1cwAtF4v8qomaFitU2AgNMqpqfQJwOEmqjd8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4d395ac7-262b-4571-b8a4-6ddbd1453a4c",
                            TwoFactorEnabled = false,
                            UserName = "Znawca"
                        },
                        new
                        {
                            Id = "bdf0715a-053f-4d3a-85e5-8013f853107e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "261b85c1-7ae6-492d-9c20-d9f31dd01f73",
                            Email = "mirkow@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIRKOW@GMAIL.COM",
                            NormalizedUserName = "MIREK123",
                            PasswordHash = "AQAAAAEAACcQAAAAEIKkA8U7M/E8s/1j3+uWdLdLRqXCWCdEYmRB9pndMQPaBitFWt/rBODorX8iaZGQUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49e2273f-70f5-495a-b5f6-5ebcba348add",
                            TwoFactorEnabled = false,
                            UserName = "mirek123"
                        },
                        new
                        {
                            Id = "9c3d4bdf-a2eb-42f5-9b67-07facff0653d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b72a7c64-e1a6-4d26-9f8f-5e9a84deeef3",
                            Email = "enowak@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ENOWAK@GMAIL.COM",
                            NormalizedUserName = "EMILKA",
                            PasswordHash = "AQAAAAEAACcQAAAAEJR5okU5QfjEWbRxXogTi9+3A9tv+1Y6aFwJ9WoZnOeFd5ko+E4vFhcTZggecfhflg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1aca2df-2d4f-4fb0-9408-0c558ae93cfb",
                            TwoFactorEnabled = false,
                            UserName = "Emilka"
                        },
                        new
                        {
                            Id = "36e158e5-3731-4976-a13f-445fe61fdddd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bbeaf624-7e06-4098-9434-0bc4b785e682",
                            Email = "jk@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JK@GMAIL.COM",
                            NormalizedUserName = "JK",
                            PasswordHash = "AQAAAAEAACcQAAAAEN/riufSGKGU2pdc+QgHHn4RIMaB3gZnzH4hf1VAKOEqX8rA3rmr7fI2R9YnDZiEKw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "993dada4-3a08-44b3-94a4-347522482000",
                            TwoFactorEnabled = false,
                            UserName = "JK"
                        },
                        new
                        {
                            Id = "f2bb93f0-3f5b-4918-9462-1d5ba0059ab4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0d6b83b-8d8f-4648-ab29-ac6da58b17f1",
                            Email = "znowakowska@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZNOWAKOWSKA@GMAIL.COM",
                            NormalizedUserName = "ZOSIAA1",
                            PasswordHash = "AQAAAAEAACcQAAAAEBbO8b958JESdBC2iH9OWbQPWb190gXUzV2bXrrMzxsNidT42khNjyKc5A+Tesls7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "866767a4-98bb-4d62-b389-0ea437fadcd3",
                            TwoFactorEnabled = false,
                            UserName = "Zosiaa1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "cef7780a-7e43-47ab-810c-c04f0114ec01",
                            ConcurrencyStamp = "5ab10a3d-040e-4054-8f31-aff48f10dca2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0",
                            ConcurrencyStamp = "578c9d97-d610-47a4-8259-1b7da4bd5036",
                            Name = "Default",
                            NormalizedName = "DEFAULT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "23e1a0ef-4a8a-462a-8219-1d3a1169f417",
                            RoleId = "cef7780a-7e43-47ab-810c-c04f0114ec01"
                        },
                        new
                        {
                            UserId = "593a9e65-5f4d-40b8-91f5-1813f577ce70",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "509de9d8-a3d5-47d9-a6b2-82c13c5dd216",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "e6f1d790-fa08-4db8-8958-4d8d171193d2",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "7b2e5361-9196-49f7-aa93-9c752fd63f19",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "1e6751b3-ecd8-4835-aee7-29274771601d",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "e32bdbc1-1892-4e41-9c69-6fcf8e40635c",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "7493442e-646b-41d4-8aa8-8b764c12eb2c",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "4be99f35-6aa1-46b4-b0d0-2c0a6545a9e2",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "a6592ad5-0033-4d24-b5c7-b5ab43d81836",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "c907b3e5-3ebc-4bf0-a733-b01c75ba8d77",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "0cf44c1c-6a00-4738-b33f-b662cf98cd7e",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "1e1a1a16-3c37-467f-ac77-e83f3061edd3",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "1fe1d8b9-40b4-4d21-9ec3-747b25fe0316",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "fb5fad4f-130e-439a-a74d-e75432c8a5d7",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "bdf0715a-053f-4d3a-85e5-8013f853107e",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "9c3d4bdf-a2eb-42f5-9b67-07facff0653d",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "36e158e5-3731-4976-a13f-445fe61fdddd",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        },
                        new
                        {
                            UserId = "f2bb93f0-3f5b-4918-9462-1d5ba0059ab4",
                            RoleId = "4b6245b3-7d2d-45ed-8c3b-af692f3363b0"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BooksApi.Models.Book", b =>
                {
                    b.HasOne("BooksApi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApi.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BooksApi.Models.Opinion", b =>
                {
                    b.HasOne("BooksApi.Models.Review", "Review")
                        .WithMany("ReviewOpinions")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApi.Models.User", "User")
                        .WithMany("ReviewOpinions")
                        .HasForeignKey("UserId");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BooksApi.Models.RefreshToken", b =>
                {
                    b.HasOne("BooksApi.Models.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BooksApi.Models.Review", b =>
                {
                    b.HasOne("BooksApi.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BooksApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BooksApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BooksApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BooksApi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BooksApi.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BooksApi.Models.Review", b =>
                {
                    b.Navigation("ReviewOpinions");
                });

            modelBuilder.Entity("BooksApi.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewOpinions");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
